### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by odysseyalive** [be1/qabc#1]
First off, this is great!  It's the only abc package left in the Ubuntu repository.

I just had a few suggestions:

1. The preferences don't seem to save -- or at least the score viewer doesn't.  I changed it to atril and when I opened the program back up, it was set back to evince.

2.  It would be nice if "editor settings" included the font size.

3.  When saving abc files, it would be nice if the system filtered the proposed name and added the .abc extension as needed.  "Recently Viewed" doesn't work if the .abc extension isn't added to the name at the time of saving the document.

4. It would be nice if the R: field printed in italics to the left above the first score as it does traditionally.

I'm a bit new to the abc format, so I really appreciate the error and warning output!  I've been using abcjs for a while and couldn't figure out why my music sounded so bad.  I was using ties instead of slurs and your program log pointed that out.

As a feature request, I would love to see a live representation of the music notes that highlight each note as you edit it.  I wonder if there is a way to embed the [abcjs package](https://github.com/paulrosen/abcjs) into this while retaining the nicer error output?  abcjs really needs a front end like this in C.

It would also be nice to have a playback instrument selection in the "Midi Synthesizer" that adds or updates the "%%MIDI program" line.

**Comment by be1** [comment]
Hello @bridgesense ,
Thank you for your suggestions. In the git repository QAbc 1.9.2 has:
1. fixed bug on always setting evince
2. font size enlargement option

I will fix 3. as soon as I can.
Can you elaborate on R: field ?
I think I will not embed abcjs. Sorry. Too much work :-)

%%MIDI program can change from line to line manually, so I think I cannot set it for the whole score as Midi Synthesizer option.

Thank you for your interest on QAbc !

**Comment by odysseyalive** [comment]
> I will fix 3. as soon as I can. Can you elaborate on R: field ? I think I will not embed abcjs. Sorry. Too much work :-)
> 

The R field is just for notating the style of music like: waltz, reel, hornpipe, etc.  Not necessary at all.

> %%MIDI program can change from line to line manually, so I think I cannot set it for the whole score as Midi Synthesizer option.

I totally understand! I'll be using this anyway.  Qabc is much more useful to me than what I was using.

Thanks, for the font adjustment!

**Comment by be1** [comment]
Oh yes, for the R field, just add `%%infoline 1` below The X field. This is an abcm2ps option (seen on http://moinejf.free.fr/abcm2ps-doc/infoline.html)

**Comment by odysseyalive** [comment]
> Oh yes, for the R field, just add `%%infoline 1` below The X field. This is an abcm2ps option (seen on http://moinejf.free.fr/abcm2ps-doc/infoline.html)

I guess they axed the infoline recently.  I just threw it onto the composer line.

All the changes are great!  Thank you!
